doctrine:
    dbal:
        mapping_types:
            beeriously_brewery_id: beeriously_brewery_id
            beeriously_brewery_name: beeriously_brewery_name
        types:
            beeriously_brewery_id:
              class: Beeriously\Brewery\Infrastructure\Type\BreweryIdType
              commented: true
            beeriously_brewery_name:
              class: Beeriously\Brewery\Infrastructure\Type\BreweryNameType
              commented: true
            beeriously_brewery_mass_volume_units_preference:
              class: Beeriously\Brewery\Infrastructure\Type\MassVolumePreferenceType
              commented: true