framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        handler_id:  Beeriously\Infrastructure\SessionHandler\SessionHandler
        name: brew_session
        cookie_httponly: true
        cookie_secure: false
        cookie_lifetime: 14400
        gc_maxlifetime: 14400
    #esi: ~
    #fragments: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

