translation:
    locales: ["us", "de"]
    symfony_profiler: # must be placed in config_dev.yml
        enabled: true
    webui:
        enabled: true
    edit_in_place:
        enabled: false
        config_name: default # the first one or one of your configs
        activator: php_translation.edit_in_place.activator
    configs:
        beeriously:
            dirs: ["%kernel.root_dir%/../templates", "%kernel.root_dir%/../src"]
            output_dir: "%kernel.root_dir%/../translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs, FOSUserBundle]