
security:
    always_authenticate_before_granting: true
    encoders:
        Beeriously\Brewer\Brewer: bcrypt

    role_hierarchy:
        ROLE_OWNER_OF_BREWERY_ACCOUNT: ROLE_BREWER
        ROLE_BREWER: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        database:
          entity:
            class: Beeriously\Brewer\Brewer
            property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: database
                csrf_token_generator: security.csrf.token_manager
                default_target_path: dashboard
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
                invalidate_session: true
            anonymous:    true

    access_control:
        - { path: '^/([a-z]+)/login', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/([a-z]+)/register', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/([a-z]+)/resetting', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/([a-z]+)/choose-language', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/([a-z]+)/public', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/([a-z]+)/admin/_trans', role: ROLE_TRANSLATOR }
        - { path: '^/([a-z]+)/', role: ROLE_USER }
        - { path: '^/([a-z]+)/dev', role: IS_AUTHENTICATED_ANONYMOUSLY }
