language: php
php:
  - 7.1
sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - APP_ENV="test"
    - APP_DEBUG=1
    - APP_SECRET=86b69684f6fe8114f978e4f02b067ab6

before_install:
  - rm .env
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v
  - ./bin/console lint:yaml config
  - ./bin/console lint:twig templates
  - composer validate --strict
  - ./vendor/bin/phpunit --configuration /app/src/Tests/Unit/phpunit.xml.dist

