language: php
php:
  - 7.1
sudo: false

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
    - PGPORT=5433
    - APP_ENV=test
    - APP_DEBUG=1
    - APP_SECRET=86b69684f6fe8114f978e4f02b067ab6

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache


before_install:
  - rm .env
  - rm .env.dist
  - mv .env.travis .env
  - composer self-update

install:
  - composer install  --no-interaction --prefer-dist

before_script:
  - export PGPASSWORD=""
  - psql -c 'CREATE DATABASE beeriously;' -U postgres -h localhost
  - psql -c "CREATE USER beerme WITH PASSWORD '64ounces';" -U postgres -h localhost
  - bin/console doctrine:migrations:migrate  --env=test --no-interaction
  - bin/console cache:clear --env=test --no-interaction
  - bin/console cache:warmup --env=test --no-interaction

script:
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v
  - ./bin/console lint:yaml config
  - ./bin/console lint:twig templates
  - composer validate --strict
  - ./vendor/bin/phpunit --configuration ./tests/Unit/phpunit.xml.dist

