###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=64ounces
        - MYSQL_DATABASE=beeriously
        - MYSQL_USER=growler
        - MYSQL_PASSWORD=64ounces
      healthcheck:
        test: "mysql --user=root --password=64ounces --execute \"SHOW DATABASES;\""
        interval: 3s
        timeout: 1s
        retries: 5
      ports:
        - "62338:3306"

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "62337:80"

    php-fpm:
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    webpack:
      build:
        context: .
        dockerfile: docker/node/Dockerfile
      working_dir: /application
      volumes:
        - .:/application

    selenium:
      image: selenium/standalone-chrome-debug
      working_dir: /application
      volumes:
        - .:/application:cached
      ports:
        - "4444:4444"
        - "62339:5900"
