version: "3.1"
services:

    postgres:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: 64ounces
      ports:
        - "127.0.0.1:62342:5432"

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "62337:80"

    php-fpm:
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    webpack:
      build:
        context: .
        dockerfile: docker/node/Dockerfile
      working_dir: /application
      volumes:
        - .:/application

    selenium:
      image: selenium/standalone-chrome-debug:3.7.1
      working_dir: /application
      volumes:
        - .:/application:cached
      ports:
        - "62339:5900"

    sauce-tunnel:
      image: henrrich/docker-sauce-connect
      command: ["-u", "user", "-k", "uuid-key"]
