_translation_webui:
    resource: "@TranslationBundle/Resources/config/routing_webui.yml"
    prefix:  /admin
  
_translation_profiler:
    resource: '@TranslationBundle/Resources/config/routing_symfony_profiler.yml'

#_translation_edit_in_place:
#    resource: '@TranslationBundle/Resources/config/routing_edit_in_place.yml'
#    prefix:  /admin
