controllers:
    resource: ../src/Controller/
    type: annotation

brewery:
    resource: ../src/Brewery/Infrastructure/Controller/
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#redirecting the homepage
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    options: { i18n: false }
    defaults:
        route: dashboard
        permanent: false
