brewery:
    resource: ../src/Brewery/Infrastructure/Controller/
    type: annotation

calculations:
    resource: ../src/Calculations/Infrastructure/Controller/
    type: annotation

dashboard:
    resource: ../src/Dashboard/Infrastructure/Controller/
    type: annotation

langauge:
    resource: ../src/Infrastructure/Language/Controller/
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


