#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
controllers:
    resource: ../src/Controller/
    type: annotation

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile