# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

jms_i18n_routing:
    default_locale: en
    locales: [en, de]
    strategy: prefix

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Doctrine\ORM\EntityManagerInterface:
        alias: 'doctrine.orm.entity_manager'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    Beeriously\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
